imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: %doctrine_cache_backend%
        result_cache_driver: %doctrine_cache_backend%
        query_cache_driver: %doctrine_cache_backend%

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            excluded_404s:
                - ^/[^/]+\.php$
                - ^/(favicon\.png|sitemap\.xml|apple-touch-icon-precomposed\.png)$
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

framework:
    session:
        cookie_secure: %force_ssl%
    validation:
        cache: %validation_cache_backend%

nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    forced_ssl:
        enabled: %force_ssl%
        hsts_max_age: 2592000 # 30 days
